version: 1

sources:
  - channel: bookworm main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240401T030239Z
  - channel: bookworm-updates main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240401T030239Z
  - channel: bookworm-security main
    url: https://snapshot-cloudflare.debian.org/archive/debian-security/20240401T030239Z

archs:
  - amd64

packages:
  - libuuid1
