"apt-get"

load(":lockfile.bzl", "lockfile")

_DEB_IMPORT_TMPL = '''\
    http_archive(
        name = "{name}",
        urls = {urls},
        sha256 = "{sha256}",
        build_file_content = """\
load("@rules_distroless//apt/private:dpkg_statusd.bzl", "dpkg_statusd")
load("@rules_distroless//distroless:defs.bzl", "flatten")

filegroup(
    name = "odata",
    srcs = ["data.tar.xz"]
)

dpkg_statusd(
    name = "statusd",
    control = ":control",
    package_name = "{package_name}",
    visibility = ["//visibility:public"],
)

flatten(
    name = "data",
    visibility = ["//visibility:public"],
    tars = [
        ":odata",
        ":statusd"
    ],
    compression = "gzip"
)

filegroup(
    name = "control",
    visibility = ["//visibility:public"],
    srcs = ["control.tar.xz"]
)
"""
    )
'''

_PACKAGE_TMPL = '''\
filegroup(
    name = "{target_name}",
    visibility = ["//visibility:public"],
    srcs = [
        {deps}
    ]
)

alias(
    name = "control",
    actual = "@{repo_name}//:control",
    visibility = ["//visibility:public"],
)
'''

def _deb_package_index_impl(rctx):
    package_defs = [
        '"""Generated by rules_distroless. DO NOT EDIT."""',
        """load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")""",
        "",
        "",
        "# buildifier: disable=function-docstring",
        "def {}_packages():".format(rctx.attr.name),
    ]

    lockf = lockfile.from_json(rctx, rctx.attr.lock)

    if len(lockf.packages()) < 1:
        package_defs.append("   pass")

    for (package) in lockf.packages():
        name = lockfile.make_package_key(
            package["name"],
            package["version"],
            package["arch"],
        )
        package_defs.append(
            _DEB_IMPORT_TMPL.format(
                name = "%s_%s" % (rctx.attr.name, package["key"]),
                package_name = package["name"],
                urls = [package["url"]],
                sha256 = package["sha256"],
            ),
        )

        rctx.file(
            "%s/%s/BUILD.bazel" % (package["name"], package["arch"]),
            rctx.attr.package_template.format(
                target_name = package["arch"],
                deps = ",\n        ".join(['"@%s_%s//:data"' % (rctx.attr.name, dep) for dep in package["dependencies"] + [name]]),
                urls = [package["url"]],
                name = package["name"],
                arch = package["arch"],
                sha256 = package["sha256"],
                repo_name = "%s_%s" % (rctx.attr.name, name),
            ),
        )

    rctx.file("packages.bzl", "\n".join(package_defs))
    rctx.file("BUILD.bazel", """
alias(
    name = "lock",
    actual = "@{}_resolution//:lock",
    tags = ["manual"],
)
exports_files(glob(['packages.bzl']))
""".format(rctx.attr.name))

deb_package_index = repository_rule(
    implementation = _deb_package_index_impl,
    attrs = {
        "lock": attr.label(),
        "package_template": attr.string(default = _PACKAGE_TMPL),
    },
)
